name: Create new comment on issue

on: 
  issues:
    types: [opened]

jobs:
  comment-with-action:
      runs-on: ubuntu-latest
      steps: 
        - name: "dump github context"
          run: echo '${{ toJSON(github.event) }}' | jq
          shell: bash
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
